apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  namespace: webapps  # change to the namespace where Jenkins is running
rules:
- apiGroups: ["", "apps", "batch", "extensions", "autoscaling", "networking.k8s.io", "policy", "rbac.authorization.k8s.io"]
  resources: [
    "pods", "services", "endpoints", "persistentvolumeclaims", "configmaps", "secrets",
    "deployments", "daemonsets", "replicasets", "statefulsets",
    "jobs", "cronjobs",
    "horizontalpodautoscalers",
    "ingresses", "networkpolicies",
    "poddisruptionbudgets", "podsecuritypolicies",
    "roles", "rolebindings", "serviceaccounts"
  ]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
